server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  output:
    ansi:
      enabled: always
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
